#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/luquibase
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Friends#123
#  jpa:
#    hibernate:
#      ddl-auto: none
#liquibase :
#  enabled: true
#  change-log: classpath:db/changelog/db.changelog-master.xml


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luquibase
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Friends#123
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: sbkpaiya13052003@gmail.com
    password: U20cs233
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true